import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.11.1:33',
  releaseNotes: {
    en_US: `Indexes far faster when you run a second, full Bitcoin node on the same server. The two chains share every block below the point they split, so a full node of either one already holds almost everything a pruned node has discarded. Those blocks were being fetched from the network one at a time; they are now read from the other node's disk when it is there. Nothing to configure. An installed second node is found and used automatically, and is checked before it is trusted: one that is itself pruned, or that has not synced far enough, is skipped with the reason in the log. Any block it cannot supply falls back to the network exactly as before, so the worst case is what happens today. The blocks it returns are checked against the hash that was asked for, so a node following the other chain cannot supply the wrong block. If you have only one node, nothing changes.`,
    es_ES: `Indexes far faster when you run a second, full Bitcoin node on the same server. The two chains share every block below the point they split, so a full node of either one already holds almost everything a pruned node has discarded. Those blocks were being fetched from the network one at a time; they are now read from the other node's disk when it is there. Nothing to configure. An installed second node is found and used automatically, and is checked before it is trusted: one that is itself pruned, or that has not synced far enough, is skipped with the reason in the log. Any block it cannot supply falls back to the network exactly as before, so the worst case is what happens today. The blocks it returns are checked against the hash that was asked for, so a node following the other chain cannot supply the wrong block. If you have only one node, nothing changes.`,
    de_DE: `Indexes far faster when you run a second, full Bitcoin node on the same server. The two chains share every block below the point they split, so a full node of either one already holds almost everything a pruned node has discarded. Those blocks were being fetched from the network one at a time; they are now read from the other node's disk when it is there. Nothing to configure. An installed second node is found and used automatically, and is checked before it is trusted: one that is itself pruned, or that has not synced far enough, is skipped with the reason in the log. Any block it cannot supply falls back to the network exactly as before, so the worst case is what happens today. The blocks it returns are checked against the hash that was asked for, so a node following the other chain cannot supply the wrong block. If you have only one node, nothing changes.`,
    pl_PL: `Indexes far faster when you run a second, full Bitcoin node on the same server. The two chains share every block below the point they split, so a full node of either one already holds almost everything a pruned node has discarded. Those blocks were being fetched from the network one at a time; they are now read from the other node's disk when it is there. Nothing to configure. An installed second node is found and used automatically, and is checked before it is trusted: one that is itself pruned, or that has not synced far enough, is skipped with the reason in the log. Any block it cannot supply falls back to the network exactly as before, so the worst case is what happens today. The blocks it returns are checked against the hash that was asked for, so a node following the other chain cannot supply the wrong block. If you have only one node, nothing changes.`,
    fr_FR: `Indexes far faster when you run a second, full Bitcoin node on the same server. The two chains share every block below the point they split, so a full node of either one already holds almost everything a pruned node has discarded. Those blocks were being fetched from the network one at a time; they are now read from the other node's disk when it is there. Nothing to configure. An installed second node is found and used automatically, and is checked before it is trusted: one that is itself pruned, or that has not synced far enough, is skipped with the reason in the log. Any block it cannot supply falls back to the network exactly as before, so the worst case is what happens today. The blocks it returns are checked against the hash that was asked for, so a node following the other chain cannot supply the wrong block. If you have only one node, nothing changes.`,
  },
  migrations: {
    // Nothing to migrate. This version only changes how blocks are fetched during indexing, not
    // what is stored: the index on disk is identical either way, so an existing one is resumed
    // rather than rebuilt.
    //
    // The `knots-rdts` remap that :30 needed lives in `v0_11_1_30.ts`, with the
    // version that introduced it, rather than being re-declared here.
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
